### ISSUE TITLE
Speed control failing on high-refresh-rate displays

### ISSUE THREAD

**Issue by pelrun** [floooh/chips-test#15]
I've acquired a fancy new laptop with a 144Hz display, and all the emulators run far too quickly.

A bit of a dive into the code shows that `clock_frame_time` is hardcoded to return a 60Hz frame time (16ms) regardless of the (much lower) true value, causing the emulation to execute too many cycles.

**Comment by floooh** [comment]
Yeah, it's a known issue but should be easy to fix (I just don't have a way to test the fix).

The frame time measurement is currently very "rigid" to prevent both microstuttering and audio glitches and the emulation to run into a "death-spiral" if a frame takes too long for some reason (for instance during debugging), or the host machine isn't fast enough to run the emulation in realtime.

Basically, everything below 24 ms frame duration is currently hardwired to a 16.6ms frame duration (60Hz), and everything above 24ms is set to 30Hz (to prevent the "death spiral"). 

I need to add additional "frame duration bands" for other common display refresh rates.

**Comment by floooh** [comment]
I have added a potential fix (https://github.com/floooh/chips-test/commit/29e987f6fe998b8c2351f35a159c0f96c9678b1c), note the call to ```stm_round_to_closest_refresh_rate()```.

I have no way to test this here though, all my displays are 60Hz. Could you give it a try and let me know if it works now?

**Comment by floooh** [comment]
PS: one thing that doesn't work currently is the delay for auto-start demos until the emulated system is ready to receive input (so most demos and games on the tinyemu webpage won't start properly). I'll keep this ticket open until this is fixed too. The emulator speed should be correct now on the most common display refresh rates now though.

**Comment by floooh** [comment]
Another reported problem: problems with keyboard input (sometimes keys aren't registered), probably because the keys are sticky for a fixed number of frames to give the emulated system enough time to scan the keyboard matrix. This also needs to be adjusted for different frame rates.

**Comment by floooh** [comment]
note to self: try to simulate a high frame rate by running the simulator at a fixed 144 (or more) frame time, hopefully that's enough to reproduce those problems.

**Comment by pelrun** [comment]
That's definitely much better on my 144Hz display, the phX and Logon's Run demos are now running at the speed I expect them to, with no audio glitches.

**Comment by floooh** [comment]
Ok, I added more fixes to make the keyboard input and start-delay frame rate independent, hopefully these were all places where timing was done with fixed frames. I'll close the ticket for now, if new problems show up, we should either reopen this ticket, or open new ones.

Thanks for reporting the bug and testing!
