### ISSUE TITLE
Hello, I want write Quiz like Eliza, which platform is best?

### ISSUE THREAD

**Issue by paklau99988** [floooh/chips-test#17]
Like this: https://8bitworkshop.com/v3.6.0/?platform=c64&file=eliza.c 
Should use kc85? Is write C no ASM knowledge. 

Your could is emulator too? How create new ROM?

Thanks

**Comment by floooh** [comment]
KC85 is a fairly exotic platform and doesn't have a C compiler (sdcc works, but that requires quite some hacking, see: https://github.com/floooh/kc85sdk)

Instead I would use C64 or Amstrad CPC, the C64 has the cc65 C compiler (https://github.com/cc65/cc65), and the Amstrad CPC should be supported by z88dk (see http://www.cpcwiki.eu/index.php/Z88DK)

**Comment by paklau99988** [comment]
Thanks you.
So write code in which IDE when use cc65 compiler for example?

**Comment by floooh** [comment]
> So write code in which IDE when use cc65 compiler for example?

I have no idea, sorry. I'd expect that there is no specific IDE support, and you'd need a vanilla text editor and command line tools
