### ISSUE TITLE
cannot open include file stdalign.h

### ISSUE THREAD

**Issue by Colourclash** [floooh/chips-test#26]
Hello,

I tried building chips-test on Windows 11 but when I do `fips build` I get "cannot open include file "stdalign.h"" on a few of the files.

Cheers

Sam

**Comment by floooh** [comment]
What's your MSVC and Windows SDK version (should be printed in the cmake output at the start of the build), for instance here:

```
 Selecting Windows SDK version 10.0.22000.0 to target Windows 6.2.9200.
-- The C compiler identification is MSVC 19.34.31935.0
-- The CXX compiler identification is MSVC 19.34.31935.0
```

MSVC has only been catching up fairly recently with C11 features (I was aware that using such "recent" C versions as C11 might cause trouble with MSVC, and in the sokol headers I'm a lot more conservative about C feature usage, but for the chips headers that's fine).

**Comment by floooh** [comment]
Lol, now I borked my Visual Studio setup (on my other Windows PC) completely by trying to figure out if Visual Studio 2019 already supports stdalign.h if a more recent Windows SDK is used...

I'll do a complete Windows update and Visual Studio reinstall, brb ;)

**Comment by Colourclash** [comment]
Here are my compiler details:

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0

Sorry you ran into trouble. Thanks for looking into it. :)

**Comment by floooh** [comment]
I think/hope you just need to run a regular Visual Studio update. I just installed VS from scratch again on that troublesome WIndows machine, and this got me ```MSVC 19.34.31942.0``` and ```Windows SDK version 10.0.22000.0``` and compilation works (before that I had VS2019 on that machine, and that failed).

I guess that stdalign.h was added **really** recently to the Windows SDK.

**Comment by Colourclash** [comment]
I updated VS and it now works. Thanks!

When I updated, I ended up with these SDK and compiler versions:

````
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.34.31942.0
-- The CXX compiler identification is MSVC 19.34.31942.0
````
