### ISSUE TITLE
Question Regarding Ports

### ISSUE THREAD

**Issue by stevehjohn** [floooh/chips-test#27]
How does one setup the ports before running a particular test?

It seems there's not provision for port data in the input.

Thanks for the awesome test suite!

Steve.

**Comment by floooh** [comment]
For the CPU tests that's currently all hardwired. For instance here I just take the lower 8 bits of the address bus (which is the 'port number', multiply it by 2 and write it back to the data bus, which is then the result of the IN instruction which caused this port read.

https://github.com/floooh/chips-test/blob/cec94e468fa26ace528c2dda684d166681d9791a/tests/z80-test.c#L62-L70

A more flexible solution would be to have a second 64KByte 'io' array similar to the mem array, where port outputs would write to and port inputs would read from, but that's not implemented anywhere.

**Comment by stevehjohn** [comment]
Thanks for the info!
