### ISSUE TITLE
Sorry, one more question. Regardingtest 0x37.

### ISSUE THREAD

**Issue by stevehjohn** [floooh/chips-test#28]
Hi,

Again, thanks for this great test suite.

I'm struggling to get my emulator to pass test 0x37 (SCF) though.

Would you be able to point me in the direction of the expected behaviour please?

Thanks,

Steve.

**Comment by floooh** [comment]
From looking at my emulator code:

- the flags S, Z and P are preserved.
- C is set.
- and the undocumented X and Y flags (bit 3 and 5) are set like the bits 3 and 5 of the A register...

Also see: https://github.com/floooh/chips/blob/05cd84e43a1070a16c4edbcaa53a761561b629b8/chips/z80.h#L629-L631

**Comment by stevehjohn** [comment]
Thank-you!
